FROM nginx:alpine

RUN addgroup -S kijani && adduser -S kijani -G kijani

# FIX ALL REQUIRED NGINX PATHS (THIS IS THE KEY PART YOU MISSED)
RUN mkdir -p /var/cache/nginx \
    /var/run \
    /var/log/nginx \
    && chown -R kijani:kijani /var/cache/nginx /var/run /var/log/nginx /usr/share/nginx/html

# Fix nginx PID path issue
RUN touch /run/nginx.pid \
    && chown -R kijani:kijani /run

COPY app/index.html /usr/share/nginx/html/index.html

USER kijani
