FROM nginx:alpine

# allow nginx runtime dirs
RUN mkdir -p /var/cache/nginx \
    && mkdir -p /var/run \
    && mkdir -p /var/log/nginx \
    && chown -R nginx:nginx /var/cache/nginx /var/run /var/log/nginx

# copy app
COPY app/index.html /usr/share/nginx/html/index.html

# switch to nginx user (safe default)
