apiVersion: v1
data:
  APP_PORT: "3000"
  DB_HOST: mysql-service
  DB_PORT: "3306"
  LOG_LEVEL: info
  MAX_CONNECTIONS: "100"
  NODE_ENV: production
kind: ConfigMap
metadata:
  name: kk-payments-config
